# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestDeployApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestDeployApp

  target 'TestDeployApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestDeployAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod "HockeySDK"